version: '3'

services:
  build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: build_all.sh

  wasm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: build_wasm.sh

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: build_and_test.sh

  shell:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: /bin/bash
    tty: true
    stdin_open: true
