name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF

    - name: Build
      run: |
        cmake --build ${{ github.workspace }}/build --config Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: ${{ github.workspace }}/build
        retention-days: 1

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install GTest
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev cmake
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: Set up GTest environment
      run: |
        # Create GTEST_ROOT environment variable
        echo "GTEST_ROOT=/usr" >> $GITHUB_ENV
        # Verify GTest libraries exist
        ls -la /usr/lib/libgtest*.a || echo "GTest libraries not found!"

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: ${{ github.workspace }}/build

    - name: Restore file permissions
      run: |
        chmod -R +x ${{ github.workspace }}/build

    - name: Configure tests
      run: |
        cmake -B ${{ github.workspace }}/build-tests -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON

    - name: Build tests
      run: |
        cmake --build ${{ github.workspace }}/build-tests --config Release

    - name: Run tests
      working-directory: ${{ github.workspace }}/build-tests
      run: |
        ctest -C Release --output-on-failure
