name: CPU Emulator CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: ${{ github.workspace }}/build
        retention-days: 1

  test-linux:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    needs: build-linux
    steps:
    - uses: actions/checkout@v3

    - name: Install GTest
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev cmake
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: Configure CMake with Tests
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON

    - name: Build with Tests
      run: cmake --build ${{ github.workspace }}/build --config Release

    - name: Run Tests
      working-directory: ${{ github.workspace }}/build
      run: ctest -C Release --output-on-failure

  build-emscripten:
    name: Build WebAssembly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12

    - name: Verify Emscripten
      run: emcc --version

    - name: Configure with Emscripten
      run: emcmake cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build WebAssembly
      run: cmake --build ${{ github.workspace }}/build --config Release

    - name: Upload WebAssembly artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wasm-build
        path: |
          ${{ github.workspace }}/build/cpu_wasm.js
          ${{ github.workspace }}/build/cpu_wasm.wasm
        retention-days: 7
